# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MyFirstCli < Formula
  desc ""
  homepage "https://github.com/vramahandry/homebrew-tools"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vramahandry/my-first-cli-go/releases/download/0.0.2/my-first-cli-go_Darwin_x86_64.tar.gz"
      sha256 "50aaa1db119fb11120e1003c34fb00f5740ec45c26279eec3445edfc85ff4bd0"

      def install
        bin.install "my-first-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vramahandry/my-first-cli-go/releases/download/0.0.2/my-first-cli-go_Darwin_arm64.tar.gz"
      sha256 "22d958c960c4ddc7e6e7fd8da391bbcabda29d35d5650ed8bc6df9a3898d4756"

      def install
        bin.install "my-first-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vramahandry/my-first-cli-go/releases/download/0.0.2/my-first-cli-go_Linux_x86_64.tar.gz"
        sha256 "8dcdb711a79d8a4304cfad648577fa1a1a04b0f22bfaede2c3639ba4c662ebff"

        def install
          bin.install "my-first-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vramahandry/my-first-cli-go/releases/download/0.0.2/my-first-cli-go_Linux_arm64.tar.gz"
        sha256 "1254583cf042a76ef32c4048e2c4dbdc18c344c1aae1e6297f5e4905241ad324"

        def install
          bin.install "my-first-cli"
        end
      end
    end
  end
end
